config/routes.rb
InspectionsOuvert::Application.routes.draw do
  filter :locale

  resources :establishments, :only => [:index, :show] do
    get :embed, :on => :collection
  end

  resources :owners, :only => [:index, :show]

  match 'embed' => 'pages#embed'
  match 'about' => 'pages#about'
  match 'statistics' => 'pages#statistics'
  match 'api' => 'pages#api'

  root :to => 'pages#home'
end

app/views/shared/_analytics.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17862637-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/shared/_embed_menu.html.haml
.left
  %ul#nav
    %li= link_to "Resto-Net", root_path
    %li.search
      = form_tag embed_establishments_path, :method => :get do
        = hidden_field_tag :direction, params[:direction]
        = hidden_field_tag :sort, params[:sort]
        = text_field_tag 'search', params[:search]
        = submit_tag t('menu.search')

app/views/shared/_footer.html.haml
%div
  = link_to t('menu.api'), api_path
  |
  = link_to t('menu.about'), about_path
%div
  = link_to image_tag("open-data-montreal-#{locale}.png"), "http://montrealouvert.net/donnees-ouvertes-questions-frequemment-demandees/?lang=#{locale}"

app/views/shared/_hr.html.haml
%hr

app/views/shared/_map.html.haml
#map_canvas
- javascript "http://maps.google.com/maps/api/js?sensor=false"
- javascript %w(markerclusterer sprintf map)
:javascript
  var establishments = #{establishments_json @establishments};
  var t = #{map_translations_json};

app/views/shared/_menu.html.haml
.left
  %ul#nav
    %li= link_to t('menu.home'), root_path
    %li= link_to t('menu.all_establishments'), establishments_path
    %li= link_to t('menu.statistics'), statistics_path
    %li= link_to t('menu.about'), about_path
    - if I18n.locale == :fr
      %li= link_to t('menu.english'), :locale => :en
    - else
      %li= link_to t('menu.french'), :locale => :fr
    %li.search= render 'shared/search_form'

app/views/shared/_search_form.html.haml
= form_tag establishments_path, :method => :get do
  = hidden_field_tag :direction, params[:direction]
  = hidden_field_tag :sort, params[:sort]
  = text_field_tag 'search', params[:search]
  = submit_tag t('menu.search')